name: flutter_saf
description: Easily access and manage files on Android using the Storage Access Framework in your Flutter apps.
version: 0.1.0
homepage: https://github.com/hamiranisahil/flutter_saf
repository: https://github.com/hamiranisahil/flutter_saf

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_saf
        pluginClass: FlutterSafPlugin
